alias ls='ls --color=auto'
alias ll='ls -lh --time-style=long-iso'
alias la='ls -lha'
alias cp='cp -i'
alias mv='mv -i'
alias ..='cd ..'
alias psqlx='psql --no-psqlrc --single-transaction --set="ON_ERROR_STOP=on"'
